author = "xj63"
title = "Algorithm Impl Notes"

# The URL the site will be built for
base_url = "https://xj63.github.io/Algorithm-Implementation-Notes"

# Use theme papermod https://github.com/cydave/zola-theme-papermod
theme = "papermod"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generate a feed file for the site
generate_feeds = true
feed_filenames = ["atom.xml"]

# Minify HTML output
minify_html = true

taxonomies = [{ name = "tags", feed = true }]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100
# Wether to produce the search index as a javascript file or as a JSON file
# Accepted value "elasticlunr_javascript" or "elasticlunr_json"
index_format = "elasticlunr_json"


[extra]
# Put all your custom variables here


[extra.papermod]
title = "Algorithm Impl Notes"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["Algorithm", "Code", "Notes"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = true
edit_post_url = "https://github.com/xj63/Algorithm-Implementation-Notes/tree/master"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
  { url = "$BASE_URL/archive", title = "Archive" },
  { url = "$BASE_URL/tags", title = "Tags" },
  { url = "$BASE_URL/search", title = "Search" },
  { url = "https://github.com/xj63/Algorithm-Implementation-Notes", title = "GitHub", is_external = true },
]

home_title = "Algorithm Impl Notes"
home_content = "Welcome to xj63's algorithm implementation notes!<br><b>Algorithm-Implementation-Notes</b> is notes on the code implementation of the corresponding algorithms in the Algorithm Design and Analysis course. <br>Do give a 🌟 on Github !<br>"
social_icons = [
  { url = "https://github.com/xj63", title = "GitHub", icon = "github" },
  { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
