[package]
name = "sort"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
libc = "0.2"
openmp-sys = "1.2.3"

[build-dependencies]
cc = "1.0"
